In [2]:
# Creating NumPy Arrays
import numpy as np

In [3]:
# Ways to create NumPy arrays:
# 1. from list - (Single DataType List)
arr = np.array([1,2,3,4,5])

# .dtype tells you what type of data is stored in the NumPy array.
# .shape tells the dimensions of an array (how many rows & columns the array has).
print(arr, type(arr), arr.dtype,arr.shape)


[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)


In [4]:
# 2. from multiple datatype list
arr2 = np.array([1,2,3,4,"Five"])
print(arr2,type(arr2),arr2.dtype) # array of strings
# Numpy arrays can contain same type of data.
# Since "Five" is a string and cannot be converted to an integer, NumPy converts all elements to strings.
# U21 means Unicode Strings

['1' '2' '3' '4' 'Five'] <class 'numpy.ndarray'> <U21


In [5]:
# Creating 2d Arrays - Matrix
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3)
print(arr3.shape) #3,3 it means 3 rows and 3 cols

# Jagged array / Ragged Array
# Numpy doesn't support Jagged arrays but python list of lists can be jagged.
# arr4 = np.array([[1,2,3],[4,5,6],[7,8,9,10]])
# print(arr4) # throws errors, since NumPy arrays require all rows to have 
# same number of elements because they store data in contiguous memory.

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [6]:
# Creating Numpy arrays using built-in functions:
arr1 = np.zeros((3,4))
print(arr1)

arr2 = np.ones((3,3)) # creates 2 dimensional array of ones
print(arr2)
arr2_a = np.ones((3,)) # creates 1 dimensional array of ones
print(arr2_a)

arr3 = np.full((2,3),5) # creates Numpy array with a mentioned value
print(arr3)

arr4 = np.eye(3) #Creates identity matrix of nxn (here 3x3),
# Identity matrix is square matrix where All diagonal elements are 1 & all non-diagonal elements are 0.
print(arr4)

start = 1
end = 20 # n-1 it means 20-1 = 19 
steps = 2
arr5 = np.arange(start,end) # Creates one dimensional array
arr5_b = np.arange(start,end,steps)
print(arr5)
print(arr5_b)

n = 3
arr6 = np.linspace(0,10,n) # creates n equally spaced values from start to end arrays.
print(arr6)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[1. 1. 1.]
[[5 5 5]
 [5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]
[ 0.  5. 10.]


#### NumPy Array Properties

In [ ]:
arrP = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

print(arrP.shape) # Dimension of array
print(arrP.size) # Total elements
print(arrP.ndim) # Number of dimension for 1D array -> 1, 2D array -> 2 and for 3D array 3.
print(arrP.dtype) # Element's data type
print(arrP.itemsize) # Size of each element in bytes - 8 for int64 

# TypeCasting in NumPy array.
# We can also explicitly change the dtype for our arrays:

# 1. Using "dtype" property
str_arr = np.array([1,2,3], dtype="U") # U stands for unicode (String)
print(str_arr,str_arr.itemsize)
float_arr = np.array([1,2,3], dtype="float64") 
print(float_arr)
print(float_arr.itemsize)
print(float_arr.dtype)

# 2. Using "astype" method.
# astype method is used for Creating a new array by converting an existing array to a specific data type.
int_arr = float_arr.astype(np.int64)
print(int_arr,int_arr.dtype)


(4, 3)
12
2
int64
8
['1' '2' '3'] 4
[1. 2. 3.]
8
float64
[1 2 3] int64


#### Operations on Arrays

In [ ]:
# There are a lot of useful operations that we can perform on our arrays:

# 1. Reshaping - Changing Dimensions
# Works when element count remains unchanged.
arrRe = np.array([1,2,3,4,5,6]) #element count 6
print(arrRe)

reshaped = arrRe.reshape((2,3)) # converts 1d array (1 row x 6 col) into (2 row x 3 col)
print(reshaped,reshaped.shape) # element count 2 x 3 = 6

flattened = reshaped.flatten() # converts multi dimensional array into 1D array.
print(flattened,flattened.shape)


# 2. Indexing (1d & 2d array)
arrI = np.array([1,2,3,4,5])
print(arr[2])

arrI2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arrI2[0][2]) # where 0 is row & 2 is column
print(arrI2[1][1])

# 3. Fancy & Boolean Indexing
# Fancy Indexing means accessing array elements using integer arrays/lists of indices rather than plain slices (:).
arrF = np.array([1,2,3,4,5,6])

# list of indices
print(arrF[[0,1,4]]) # print nums at given indices 

# array of indices
print(arrF[np.array([0,1,4])])

arrF2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
# print(arrF2[[0,2],[1,1],[2,2]]) # won't work because Number of index arrays must equal the number of dimensions of the array
print(arrF2[[0,2],[1,1]]) # rows -> [0,2] cols -> [1,1] and Numpy read like this [0,1] and then [2,1]
print(arrF2[[0,1,2],[2,1,2]]) # rows -> [0,1,2] cols -> [2,1,2] & numpy read like this [0,2],[1,1],[2,2]


# Boolean Masking or Indexing means selecting array elements using a boolean (True/False) condition.
arrB = np.array([1,2,3,4,5,6])
print(arrB[arrB>2]) # gives values greater than 2
print(arrB[arrB % 2 == 0]) # gives even number

# 4. Slicing - means extracting a part of an array using a range of indices.
arrS = np.array([1,2,3,4,5,6,7])
print(arrS[2:6]) # end - 1 (6-1)
print(arrS[:6])
print(arrS[3:])
print(arrS[::2])

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]] (2, 3)
[1 2 3 4 5 6] (6,)
3
3
5
[1 2 5]
[1 2 5]
[2 8]
[3 5 9]
[3 4 5 6]
[2 4 6]
[3 4 5 6]
[1 2 3 4 5 6]
[4 5 6 7]
[1 3 5 7]


#### Copy V/s View

In [ ]:
# Slicing in Python Lists and NumPy array may look same but 
# their inner working is different.

# In python lists -> slicing creates a new copy in the memory.
# In NumPy arrays -> slicing creates a view, view means sliced part of array which is not a copy instead it shares the same memory as the original array, since 
# no new copy of memory is created, it's memory efficient.

# So, in short views are fast and memory efficient (no data duplication).
# Copies are safe but slower and use more memory.

py_list = [1,2,3,4,5]
copy_list = py_list[1:4]
copy_list[1] = 333 #re-assigning

print(copy_list)
print(py_list) #remians same

np_arr = np.array([1,2,3,4,5])
view_arr = np_arr[1:4] 
view_arr[1] = 333

print(view_arr)
print(np_arr) # changes, since actual memory addresses are used & viewed.


# To create a copy for array
copy_arr = np_arr[1:4].copy()
copy_arr[2] = 444
print(copy_arr)
print(np_arr)


[2, 333, 4]
[1, 2, 3, 4, 5]
[  2 333   4]
[  1   2 333   4   5]
[  2 333 444]
[  1   2 333   4   5]
