In [1]:
# Creating NumPy Arrays
import numpy as np

In [ ]:
# Ways to create NumPy arrays:
# 1. from list - (Single DataType List)
arr = np.array([1,2,3,4,5])

# .dtype tells you what type of data is stored in the NumPy array.
# .shape tells the dimensions of an array (how many rows & columns the array has).
print(arr, type(arr), arr.dtype,arr.shape)


[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)


In [ ]:
# 2. from multiple datatype list
arr2 = np.array([1,2,3,4,"Five"])
print(arr2,type(arr2),arr2.dtype) # array of strings
# Numpy arrays can contain same type of data.
# Since "Five" is a string and cannot be converted to an integer, NumPy converts all elements to strings.
# U21 means Unicode Strings

['1' '2' '3' '4' 'Five'] <class 'numpy.ndarray'> <U21


In [ ]:
# Creating 2d Arrays - Matrix
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3)
print(arr3.shape) #3,3 it means 3 rows and 3 cols

# Jagged array / Ragged Array
# Numpy doesn't support Jagged arrays but python list of lists can be jagged.
# arr4 = np.array([[1,2,3],[4,5,6],[7,8,9,10]])
# print(arr4) # throws errors, since NumPy arrays require all rows to have 
# same number of elements because they store data in contiguous memory.

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [41]:
# Creating Numpy arrays using built-in functions:
arr1 = np.zeros((3,4))
print(arr1)

arr2 = np.ones((3,3)) # creates 2 dimensional array of ones
print(arr2)
arr2_a = np.ones((3,)) # creates 1 dimensional array of ones
print(arr2_a)

arr3 = np.full((2,3),5) # creates Numpy array with a mentioned value
print(arr3)

arr4 = np.eye(3) #Creates identity matrix of nxn (here 3x3),
# Identity matrix is square matrix where All diagonal elements are 1 & all non-diagonal elements are 0.
print(arr4)

start = 1
end = 20 # n-1 it means 20-1 = 19 
steps = 2
arr5 = np.arange(start,end) # Creates one dimensional array
arr5_b = np.arange(start,end,steps)
print(arr5)
print(arr5_b)

n = 3
arr6 = np.linspace(0,10,n) # creates n equally spaced values from start to end arrays.
print(arr6)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[1. 1. 1.]
[[5 5 5]
 [5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]
[ 0.  5. 10.]


In [ ]:
# NumPy Array Properties
arrP = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

print(arrP.shape) # Dimension of array
print(arrP.size) # Total elements
print(arrP.ndim) # Number of dimension for 1D array -> 1, 2D array -> 2 and for 3D array 3.
print(arrP.dtype) # Element's data type
print(arrP.itemsize) # Size of each element in bytes - 8 for int64 

# TypeCasting in NumPy array.
# We can also explicitly change the dtype for our arrays:

# 1. Using "dtype" property
str_arr = np.array([1,2,3], dtype="U") # U stands for unicode (String)
print(str_arr,str_arr.itemsize)
float_arr = np.array([1,2,3], dtype="float64") 
print(float_arr)
print(float_arr.itemsize)
print(float_arr.dtype)

# 2. Using "astype" method.
# astype method is used for Creating a new array by converting an existing array to a specific data type.
int_arr = float_arr.astype(np.int64)
print(int_arr,int_arr.dtype)



(4, 3)
12
2
int64
8
['1' '2' '3'] 4
[1. 2. 3.]
8
float64
[1 2 3] int64
