##### Mathematical Functions
- NumPy is massive & provides a wide range of built-in mathematical functions that are highly optimized and can operate element-wise on arrays.

In [12]:
# Aggregate Functions
# Functions that perform a calculation on a set of values and return a single summary value.

import numpy as np
arr = np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr)) # returns index of min value 
print(np.argmax(arr)) # returns index of max value 
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))


15
120
1
5
0
4
3.0
3.0
1.4142135623730951
2.0


In [16]:
# Power functions
# Power functions are functions that raise numbers (or arrays) to a certain exponent.

arr2 = np.array([1,2,3,4,5])
print(np.square(arr2)) 
print(np.sqrt(arr2)) # returns square root of all elements
print(np.pow(arr,3)) #  returns a raise to the power b (a here is arr elements)

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [17]:
# Log & Exponential Functions
print(np.log(arr2))  
print(np.log10(arr2))  
print(np.log2(arr2))  
print(np.exp(arr2)) 

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [ ]:
# Rounding Functions
print(np.round(2.578)) # rounds off to nearest value 
print(np.round(2.478)) # rounds off to nearest value
print(np.ceil(4.278)) # rounds up
print(np.floor(4.999)) # rounds down
print(np.trunc(2.678)) # truncates (removes) the fractional or decimal part

3.0
2.0
5.0
4.0
2.0


In [ ]:
# Miscellaneous Functions
arr = np.array([1, 2, -5, 3, 8, -4, 2, 5]) 

print(np.abs(arr)) # returns absolute value
print(np.sort(arr)) # returns sorted(arranges in increasing order) values
print(np.unique(arr)) 

# There are many other built-in functions that we will use and learn about in later chapters. 

[1 2 5 3 8 4 2 5]
[-5 -4  1  2  2  3  5  8]
[-5 -4  1  2  3  5  8]
