In [ ]:
# Vectorizaton & Broadcasting are 2 most powerful features for fast numerical computations.

# Vectorization means performing operations on entire arrays at once without explicit Python loops.  
# For this numpy uses C-level implementation internally, much faster than Python loops & makes code shorter,cleaner and faster.
import numpy as np
arr = np.array([1,2,3,4,5])

sq_arr = arr**2
print(sq_arr)

arr2 = np.array([6,7,8,9,10])
print(arr2 + 1)

[[  1   4   9  16  25]
 [ 36  49  64  81 100]]
[ 7  8  9 10 11]


In [ ]:
# Broadcasting means allowing NumPy to automatically expand arrays of different shapes so 
# that arithmetic operations can be performed. 
# It’s basically scaling arrays without using extra memory. 
# Broadcasting can only take place when the arrays are of compatible shape. 
# So NumPy compares shapes of arrays from right to left. 
# For the array to be compatible, all dimensions must either be: 

# Equal
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)

# one of the array's dimension is 1 or missing, so that the array can be stretched to match the other's array dimension.
a1 = np.array([[2,4,5,6],[7,8,9,10]]) # shape (2,4)
b2 = np.array([[2,2,2,2]]) # shape (missing,4) NumPy treats the missing dimension as 1, so the shape becomes (1, 4)

# Numpy first compares shapes of arrays from right to left:
# a1's 4 will be compared with b2's 4 since both are same, numpy move to left
# Now since b2's shape contains 1 it can be stretched to match with 2 of a1's , so broadcasting is allowed.
# b2 will become [[2, 2, 2, 2],[2, 2, 2, 2]]
print(a1+b2)

# ex 2: 
c1 = np.array([[1,2,3,4],[5,6,7,8]]) #(2,4)
d1 = np.array([[2,2,2,2],[1,1,1,1,],[3,3,3,3]]) #(3,4)
# print(a1 + b2) # will throw error because 4 with 4 is matched but 2 and 3 will not.

# ex 3:
m1 = np.array([6,7,8,9,10]) # 1d array -> (5,)
m2 = np.array([1]) # 1d array -> (1,)
# numpy compares right to left -> missing to missing, then 5 to 1 and sees that 1 can be stretched to 5.
# so [1] becomes [1,1,1,1,1]
print(m1+m2)

# ex 4:
arr5 = np.array([[1,2,3,4,5],[6,7,8,9,10]]) # (2,5)
print(arr5 + 2)
# 2 here is treated as 1d array with shape(1,missing)
# NumPy treats the missing dimensions as 1
# arr5's dimension (2,5) will be matched with (1,1)
# since, they become 1 they can be stretched and 2 become like this:
# [[2,2,2,2,2],[2,2,2,2,2]] (2,5) Now addition will done.

[5 7 9]
[[ 4  6  7  8]
 [ 9 10 11 12]]
[ 7  8  9 10 11]
[[ 3  4  5  6  7]
 [ 8  9 10 11 12]]


##### A very common use of broadcasting is in vector normalization, which is widely used in machine learning and data preprocessing. 
#### For example: Vector normalization has various types one of the type of it is standard vector normalization, where we transform an array so that it has: Mean = 0 and Standard deviation = 1

In [15]:
# Standard Vector Normalization
arrN = np.array([[1,2],[3,4]])

mean = np.mean(arrN)
std_dev = np.std(arrN)

normalized_arr = (arrN-mean)/std_dev
print(normalized_arr)

# Now when you calculate mean and standard deviation of 
# normalized array you'll get mean = 0 and standard deviation = 1.
print(np.mean(normalized_arr))
print(np.std(normalized_arr))

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
0.0
1.0
