#### Multi-dimensional Arrays
- A Numpy array can have any number of dimensions (1D,2D,3D & so on). Each dimension is called an axis.
    - 1D array has 1 axis (axis0).
    - 2D array has 2 axes (axis0 = rows, axis1 = columns)
    - 3D array has 3 axes (axis0 = depth/layer, axis1 = rows in each layer, axis2 = columns in each layer)

In [7]:
# 1d array
import numpy as np
arr1d = np.array([1,2,3])
print(arr1d.ndim)

# 2d array
arr2d = np.array([[1,2,3],[4,5,6]])
print(arr2d.ndim)

# 3d array - combination of multiple 2d array
arr3d = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,12,12]]
])
print(arr3d)
print(arr3d.ndim)
print(f"Accessing element 3 from 3d array:{arr3d[0][0][2]}")

# 2d array is basically used for grayscale images when ML&DL models workes with images.
# Whereas,3d array is used for color images.


1
2
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 12 12]]]
3
Accessing element 3 from 3d array:3


#### We can perform operations on 2d and 3d arrays, axes wise:

In [ ]:
# 2D array has 2 axes(axes = 0 for row (vertically), axes = 1 for column (horizontally))
# 3D array has 3 axes (axes = 0 for depth/height, axes = 1 for row, axes = 2 for column)

# 2d array
arr = np.array([[1,2,3],[4,5,6]])
print(np.sum(arr))
print(np.sum(arr,axis=0)) 
print(np.sum(arr,axis=1)) 

# Slicing on 2d array
arrS = np.array([[1,2,3],[4,5,6]])
print(arrS[0:2,1:2])


21
[5 7 9]
[ 6 15]
[[1 2]
 [4 5]]


In [23]:
# 3D array & Operations on 3D arrays

# 2 x 3 x 3
arr3 = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]]
]) 
print(arr3)
print(arr3.shape)

# Operations:Indexing(accessing)
print(arr3[0][0][2])

# Slicing
print(arr3[0,0:3,2])

# Updating data
arr3[0:,0:,0:1] = 12
print(arr3)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
(2, 3, 3)
3
[3 6 9]
[[[12  2  3]
  [12  5  6]
  [12  8  9]]

 [[12 11 12]
  [12 14 15]
  [12 17 18]]]
